const AUTH_FETCH_REQUESTED = 'AUTH_FETCH_REQUESTED'
const AUTH_FETCH_SUCCEEDED = 'AUTH_FETCH_SUCCEEDED'
const AUTH_FETCH_FAILED = 'AUTH_FETCH_FAILED'

const TODOS_FETCH_SUCCEEDED = 'TODOS_FETCH_SUCCEEDED'
const TODOS_FETCH_FAILED = 'TODOS_FETCH_FAILED'

const CREATE_TODO = 'CREATE_TODO'
const UPDATE_TODO = 'UPDATE_TODO'
const DELETE_TODO = 'DELETE_TODO'

const RUN_GLOBAL_MSG = 'RUN_GLOBAL_MSG'

export {
  AUTH_FETCH_REQUESTED,
  AUTH_FETCH_SUCCEEDED,
  AUTH_FETCH_FAILED,

  TODOS_FETCH_SUCCEEDED,
  TODOS_FETCH_FAILED,

  CREATE_TODO,
  UPDATE_TODO,
  DELETE_TODO,

  RUN_GLOBAL_MSG
}